import { expect, it } from "vitest";
import materialTailwind from ".";

// This test is rather simple and more of a smoke test to ensure in CI that we build the dependency correctly
it("Can create a Material design TailwindCSS configuration", () => {
  const plugin = materialTailwind({ source: "#0c1445" });

  expect(plugin).toMatchInlineSnapshot(`
    {
      "config": {
        "theme": {
          "borderRadius": {
            "full": "100%",
            "lg": "1rem",
            "md": "0.75rem",
            "none": "0px",
            "sm": "0.5rem",
            "xl": "1.75rem",
            "xs": "0.25rem",
          },
          "boxShadow": {
            "elevation-dark-level-1": "0px 1px 2px 0px rgba(0, 0, 0, 0.3), 0px 1px 3px 1px rgba(0, 0, 0, 0.15)",
            "elevation-dark-level-2": "0px 1px 2px 0px rgba(0, 0, 0, 0.3), 0px 2px 6px 2px rgba(0, 0, 0, 0.15)",
            "elevation-dark-level-3": "0px 1px 3px 0px rgba(0, 0, 0, 0.3), 0px 4px 8px 3px rgba(0, 0, 0, 0.15)",
            "elevation-dark-level-4": "0px 2px 3px 0px rgba(0, 0, 0, 0.3), 0px 6px 10px 4px rgba(0, 0, 0, 0.15)",
            "elevation-dark-level-5": "0px 4px 4px 0px rgba(0, 0, 0, 0.3), 0px 8px 12px 6px rgba(0, 0, 0, 0.15)",
            "elevation-light-level-1": "0px 1px 3px 1px rgba(0, 0, 0, 0.15), 0px 1px 2px 0px rgba(0, 0, 0, 0.3)",
            "elevation-light-level-2": "0px 2px 6px 2px rgba(0, 0, 0, 0.15), 0px 1px 2px 0px rgba(0, 0, 0, 0.3)",
            "elevation-light-level-3": "0px 1px 3px 0px rgba(0, 0, 0, 0.3), 0px 4px 8px 3px rgba(0, 0, 0, 0.15)",
            "elevation-light-level-4": "0px 2px 3px 0px rgba(0, 0, 0, 0.3), 0px 6px 10px 4px rgba(0, 0, 0, 0.15)",
            "elevation-light-level-5": " 0px 4px 4px 0px rgba(0, 0, 0, 0.3), 0px 8px 12px 6px rgba(0, 0, 0, 0.15)",
            "none": "none",
          },
          "colors": {
            "dark": {
              "background": "#131318",
              "error": "#ffb4ab",
              "error-container": "#93000a",
              "inverse-on-surface": "#303036",
              "inverse-primary": "#525a92",
              "inverse-surface": "#e4e1e9",
              "neutral-palette-key-color": "#77767d",
              "neutral-variant-palette-key-color": "#767680",
              "on-background": "#e4e1e9",
              "on-error": "#690005",
              "on-error-container": "#ffdad6",
              "on-primary": "#232c61",
              "on-primary-container": "#dfe0ff",
              "on-primary-fixed": "#0c154b",
              "on-primary-fixed-variant": "#3a4279",
              "on-secondary": "#2d2f42",
              "on-secondary-container": "#e0e1f9",
              "on-secondary-fixed": "#181a2c",
              "on-secondary-fixed-variant": "#434559",
              "on-surface": "#e4e1e9",
              "on-surface-variant": "#c7c5d0",
              "on-tertiary": "#45263d",
              "on-tertiary-container": "#ffd7f0",
              "on-tertiary-fixed": "#2d1227",
              "on-tertiary-fixed-variant": "#5d3c54",
              "outline": "#90909a",
              "outline-variant": "#46464f",
              "primary": "#bbc3ff",
              "primary-container": "#3a4279",
              "primary-fixed": "#dfe0ff",
              "primary-fixed-dim": "#bbc3ff",
              "primary-palette-key-color": "#6b73ad",
              "scrim": "#000000",
              "secondary": "#c4c5dd",
              "secondary-container": "#434559",
              "secondary-fixed": "#e0e1f9",
              "secondary-fixed-dim": "#c4c5dd",
              "secondary-palette-key-color": "#74768c",
              "shadow": "#000000",
              "surface": "#131318",
              "surface-bright": "#39393f",
              "surface-container": "#1f1f25",
              "surface-container-high": "#29292f",
              "surface-container-highest": "#34343a",
              "surface-container-low": "#1b1b21",
              "surface-container-lowest": "#0d0e13",
              "surface-dim": "#131318",
              "surface-tint": "#bbc3ff",
              "surface-variant": "#46464f",
              "tertiary": "#e6bad7",
              "tertiary-container": "#5d3c54",
              "tertiary-fixed": "#ffd7f0",
              "tertiary-fixed-dim": "#e6bad7",
              "tertiary-palette-key-color": "#926c86",
            },
            "error": {
              "0": "#000000",
              "10": "#410002",
              "100": "#ffffff",
              "15": "#540003",
              "20": "#690005",
              "25": "#7e0007",
              "30": "#93000a",
              "35": "#a80710",
              "40": "#ba1a1a",
              "5": "#2d0001",
              "50": "#de3730",
              "60": "#ff5449",
              "70": "#ff897d",
              "80": "#ffb4ab",
              "90": "#ffdad6",
              "95": "#ffedea",
              "98": "#fff8f7",
              "99": "#fffbff",
            },
            "light": {
              "background": "#fbf8ff",
              "error": "#ba1a1a",
              "error-container": "#ffdad6",
              "inverse-on-surface": "#f2eff7",
              "inverse-primary": "#bbc3ff",
              "inverse-surface": "#303036",
              "neutral-palette-key-color": "#77767d",
              "neutral-variant-palette-key-color": "#767680",
              "on-background": "#1b1b21",
              "on-error": "#ffffff",
              "on-error-container": "#410002",
              "on-primary": "#ffffff",
              "on-primary-container": "#0c154b",
              "on-primary-fixed": "#0c154b",
              "on-primary-fixed-variant": "#3a4279",
              "on-secondary": "#ffffff",
              "on-secondary-container": "#181a2c",
              "on-secondary-fixed": "#181a2c",
              "on-secondary-fixed-variant": "#434559",
              "on-surface": "#1b1b21",
              "on-surface-variant": "#46464f",
              "on-tertiary": "#ffffff",
              "on-tertiary-container": "#2d1227",
              "on-tertiary-fixed": "#2d1227",
              "on-tertiary-fixed-variant": "#5d3c54",
              "outline": "#767680",
              "outline-variant": "#c7c5d0",
              "primary": "#525a92",
              "primary-container": "#dfe0ff",
              "primary-fixed": "#dfe0ff",
              "primary-fixed-dim": "#bbc3ff",
              "primary-palette-key-color": "#6b73ad",
              "scrim": "#000000",
              "secondary": "#5b5d72",
              "secondary-container": "#e0e1f9",
              "secondary-fixed": "#e0e1f9",
              "secondary-fixed-dim": "#c4c5dd",
              "secondary-palette-key-color": "#74768c",
              "shadow": "#000000",
              "surface": "#fbf8ff",
              "surface-bright": "#fbf8ff",
              "surface-container": "#efedf4",
              "surface-container-high": "#e9e7ef",
              "surface-container-highest": "#e4e1e9",
              "surface-container-low": "#f5f2fa",
              "surface-container-lowest": "#ffffff",
              "surface-dim": "#dbd9e0",
              "surface-tint": "#525a92",
              "surface-variant": "#e3e1ec",
              "tertiary": "#77536c",
              "tertiary-container": "#ffd7f0",
              "tertiary-fixed": "#ffd7f0",
              "tertiary-fixed-dim": "#e6bad7",
              "tertiary-palette-key-color": "#926c86",
            },
            "neutral": {
              "0": "#000000",
              "10": "#1b1b21",
              "100": "#ffffff",
              "15": "#25252b",
              "20": "#303036",
              "25": "#3b3b41",
              "30": "#46464c",
              "35": "#525258",
              "40": "#5e5e64",
              "5": "#101116",
              "50": "#77767d",
              "60": "#919097",
              "70": "#acaab1",
              "80": "#c7c5cd",
              "90": "#e4e1e9",
              "95": "#f2eff7",
              "98": "#fbf8ff",
              "99": "#fffbff",
            },
            "neutral-variant": {
              "0": "#000000",
              "10": "#1a1b23",
              "100": "#ffffff",
              "15": "#25252d",
              "20": "#2f3038",
              "25": "#3a3b43",
              "30": "#46464f",
              "35": "#52525b",
              "40": "#5e5e67",
              "5": "#101018",
              "50": "#767680",
              "60": "#90909a",
              "70": "#abaab4",
              "80": "#c7c5d0",
              "90": "#e3e1ec",
              "95": "#f1effa",
              "98": "#fbf8ff",
              "99": "#fffbff",
            },
            "primary": {
              "0": "#000000",
              "10": "#0c154b",
              "100": "#ffffff",
              "15": "#182055",
              "20": "#232c61",
              "25": "#2f376c",
              "30": "#3a4279",
              "35": "#464e85",
              "40": "#525a92",
              "5": "#010841",
              "50": "#6b73ad",
              "60": "#858dc8",
              "70": "#9fa7e5",
              "80": "#bbc3ff",
              "90": "#dfe0ff",
              "95": "#f0efff",
              "98": "#fbf8ff",
              "99": "#fffbff",
            },
            "secondary": {
              "0": "#000000",
              "10": "#181a2c",
              "100": "#ffffff",
              "15": "#222537",
              "20": "#2d2f42",
              "25": "#383a4d",
              "30": "#434559",
              "35": "#4f5165",
              "40": "#5b5d72",
              "5": "#0d1021",
              "50": "#74768b",
              "60": "#8e8fa6",
              "70": "#a8a9c1",
              "80": "#c4c5dd",
              "90": "#e0e1f9",
              "95": "#f0efff",
              "98": "#fbf8ff",
              "99": "#fffbff",
            },
            "source": "#0c1445",
            "tertiary": {
              "0": "#000000",
              "10": "#2d1227",
              "100": "#ffffff",
              "15": "#391c32",
              "20": "#45263d",
              "25": "#513148",
              "30": "#5d3c54",
              "35": "#6a4860",
              "40": "#77536c",
              "5": "#21071c",
              "50": "#916c86",
              "60": "#ad85a0",
              "70": "#c99fbb",
              "80": "#e6bad7",
              "90": "#ffd7f0",
              "95": "#ffecf6",
              "98": "#fff7f9",
              "99": "#fffbff",
            },
          },
          "extend": {
            "spacing": {
              "compact": "1rem",
              "expanded": "1.5rem",
              "extraLarge": "1.5rem",
              "large": "1.5rem",
              "medium": "1.5rem",
            },
            "transitionTimingFunction": {
              "accelerate": "cubic-bezier(0.3, 0, 1, 1)",
              "decelerate": "cubic-bezier(0, 0, 0, 1)",
              "emphasized": "linear(
          0,
          0.002,
          0.01 3.6%,
          0.034,
          0.074 9.1%,
          0.128 11.4%,
          0.194 13.4%,
          0.271 15%,
          0.344 16.1%,
          0.544,
          0.66 20.6%,
          0.717 22.4%,
          0.765 24.6%,
          0.808 27.3%,
          0.845 30.4%,
          0.883 35.1%,
          0.916 40.6%,
          0.942 47.2%,
          0.963 55%,
          0.979 64%,
          0.991 74.4%,
          0.998 86.4%,
          1
        )",
              "emphasized-accelerate": "cubic-bezier(0.3, 0, 0.8, 0.15)",
              "emphasized-decelerate": "cubic-bezier(0.05, 0.7, 0.1, 1)",
              "linear": "linear",
              "standard": "cubic-bezier(0.2, 0, 0, 1)",
            },
          },
          "fontFamily": [Function],
          "fontSize": {
            "body-lg": [
              "1rem",
              {
                "fontWeight": "400",
                "letterSpacing": "0.5px",
                "lineHeight": "1.5rem",
              },
            ],
            "body-md": [
              "0.875rem",
              {
                "fontWeight": "400",
                "letterSpacing": "0.25px",
                "lineHeight": "1.25rem",
              },
            ],
            "body-sm": [
              "0.75rem",
              {
                "fontWeight": "400",
                "letterSpacing": "0.4px",
                "lineHeight": "1rem",
              },
            ],
            "display-lg": [
              "3.5625rem",
              {
                "fontWeight": "400",
                "letterSpacing": "-0.25px",
                "lineHeight": "4rem",
              },
            ],
            "display-md": [
              "2.8125rem",
              {
                "fontWeight": "400",
                "letterSpacing": "0px",
                "lineHeight": "3.25rem",
              },
            ],
            "display-sm": [
              "2.25rem",
              {
                "fontWeight": "400",
                "letterSpacing": "0px",
                "lineHeight": "2.75rem",
              },
            ],
            "headline-lg": [
              "2rem",
              {
                "fontWeight": "400",
                "letterSpacing": "0px",
                "lineHeight": "2.5rem",
              },
            ],
            "headline-md": [
              "1.75rem",
              {
                "fontWeight": "400",
                "letterSpacing": "0px",
                "lineHeight": "2.25rem",
              },
            ],
            "headline-sm": [
              "1.5rem",
              {
                "fontWeight": "400",
                "letterSpacing": "0px",
                "lineHeight": "2rem",
              },
            ],
            "label-lg": [
              "0.875rem",
              {
                "fontWeight": "500",
                "letterSpacing": "0.10px",
                "lineHeight": "1.25rem",
              },
            ],
            "label-md": [
              "0.75rem",
              {
                "fontWeight": "500",
                "letterSpacing": "0.5px",
                "lineHeight": "1rem",
              },
            ],
            "label-sm": [
              "0.675rem",
              {
                "fontWeight": "500",
                "letterSpacing": "0.5px",
                "lineHeight": "1rem",
              },
            ],
            "title-lg": [
              "1.375rem",
              {
                "fontWeight": "400",
                "letterSpacing": "0px",
                "lineHeight": "1.75rem",
              },
            ],
            "title-md": [
              "1rem",
              {
                "fontWeight": "500",
                "letterSpacing": "0.15px",
                "lineHeight": "1.5rem",
              },
            ],
            "title-sm": [
              "0.875rem",
              {
                "fontWeight": "500",
                "letterSpacing": "0.10px",
                "lineHeight": "1.25rem",
              },
            ],
          },
          "fontWeight": {
            "body-lg": "400",
            "body-md": "400",
            "body-sm": "400",
            "display-lg": "400",
            "display-md": "400",
            "display-sm": "400",
            "headline-lg": "400",
            "headline-md": "400",
            "headline-sm": "400",
            "label-lg": "500",
            "label-md": "500",
            "label-sm": "500",
            "title-lg": "400",
            "title-md": "500",
            "title-sm": "500",
          },
          "letterSpacing": {
            "body-lg": "0.5px",
            "body-md": "0.25px",
            "body-sm": "0.4px",
            "display-lg": "-0.25px",
            "display-md": "0px",
            "display-sm": "0px",
            "headline-lg": "0px",
            "headline-md": "0px",
            "headline-sm": "0px",
            "label-lg": "0.10px",
            "label-md": "0.5px",
            "label-sm": "0.5px",
            "title-lg": "0px",
            "title-md": "0.15px",
            "title-sm": "0.10px",
          },
          "lineHeight": {
            "body-lg": "1.5rem",
            "body-md": "1.25rem",
            "body-sm": "1rem",
            "display-lg": "4rem",
            "display-md": "3.25rem",
            "display-sm": "2.75rem",
            "headline-lg": "2.5rem",
            "headline-md": "2.25rem",
            "headline-sm": "2rem",
            "label-lg": "1.25rem",
            "label-md": "1rem",
            "label-sm": "1rem",
            "title-lg": "1.75rem",
            "title-md": "1.5rem",
            "title-sm": "1.25rem",
          },
          "transitionDuration": {
            "extra-long-1": "700ms",
            "extra-long-2": "800ms",
            "extra-long-3": "900ms",
            "extra-long-4": "1s",
            "long-1": "450ms",
            "long-2": "500ms",
            "long-3": "550ms",
            "long-4": "600ms",
            "medium-1": "250ms",
            "medium-2": "300ms",
            "medium-3": "350ms",
            "medium-4": "400ms",
            "none": "0ms",
            "short-1": "50ms",
            "short-2": "100ms",
            "short-3": "150ms",
            "short-4": "200ms",
          },
          "zIndex": {
            "elevation-level-0": "0",
            "elevation-level-1": "1",
            "elevation-level-2": "3",
            "elevation-level-3": "6",
            "elevation-level-4": "8",
            "elevation-level-5": "12",
          },
        },
      },
      "handler": [Function],
    }
  `);
});
