name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout the repository
        # v7.0.1
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - name: Install pnpm
        # v6.0.10
        # Version comes from the `packageManager` field in package.json
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86
      - name: Install Node.js
        # v7.0.0
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version: lts/*
          package-manager-cache: false
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts
      - name: Test and ensure dependencies were built as expected
        run: pnpm test
      - name: Create type definitions
        run: pnpm create-definitions
